# Generated by Django 4.2.2 on 2023-06-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_backend', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='dating_backend.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='static/avatars/'),
        ),
    ]
