# Generated by Django 4.2.2 on 2023-06-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_backend', '0004_user_liked_users_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_users',
            field=models.ManyToManyField(blank=True, to='dating_backend.user'),
        ),
    ]
