# Generated by Django 4.2.2 on 2023-06-09 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_backend', '0005_alter_user_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
